package x509pop

import (
	"crypto/ecdsa"
	"crypto/rsa" //nolint: gosec // SHA1 use is according to specification
	"crypto/x509"
	"math/big"

	"github.com/spiffe/go-spiffe/v2/spiffeid"
	"github.com/spiffe/spire/pkg/common/agentpathtemplate"
)

const (
	nonceLen = 32

	// PluginName for X.509 Proof of Possession
	PluginName = "x509pop"
)

// DefaultAgentPathTemplate is the default template
var DefaultAgentPathTemplateCN = agentpathtemplate.MustParse("/{{ .PluginName }}/{{ .Fingerprint }}")
var DefaultAgentPathTemplateSVID = agentpathtemplate.MustParse("/{{ .PluginName }}/{{ .SVIDPathTrimmed }}")

type agentPathTemplateData struct {
	*x509.Certificate
	SerialNumberHex string
	Fingerprint     string
	PluginName      string
	TrustDomain     string
	SVIDPathTrimmed string
	URISanSelectors map[string]string
}

type AttestationData struct {
	// DER encoded x509 certificate chain leading back to the trusted root. The
	// leaf certificate comes first.
	Certificates [][]byte `json:"certificates"`
}

type RSASignatureChallenge struct {
	// Nonce is the nonce generated by the challenger.
	Nonce []byte `json:"nonce"`
}

type RSASignatureResponse struct {
	// Nonce is the nonce generated by the responder.
	Nonce []byte `json:"nonce"`

	// Signature is the RSA signature of the combined challenger and responder
	// nonces.
	Signature []byte `json:"signature"`
}

type ECDSASignatureChallenge struct {
	// Nonce is the nonce generated by the challenger.
	Nonce []byte `json:"nonce"`
}

type ECDSASignatureResponse struct {
	// Nonce is the nonce generated by the responder.
	Nonce []byte `json:"nonce"`

	// R value of the ECDSA signature of the combined challenger and responder
	// nonces.
	R []byte `json:"r"`

	// S value of the ECDSA signature of the combined challenger and responder
	// nonces.
	S []byte `json:"s"`
}

type Challenge struct {
	RSASignature   *RSASignatureChallenge   `json:"rsa_signature"`
	ECDSASignature *ECDSASignatureChallenge `json:"ecdsa_signature"`
}

type Response struct {
	RSASignature   *RSASignatureResponse   `json:"rsa_signature"`
	ECDSASignature *ECDSASignatureResponse `json:"ecdsa_signature"`
}

func GenerateChallenge(cert *x509.Certificate) (*Challenge, error) {
	_ = "STUB: not implemented"
	// ensure that the public key is intended to be used for digital signatures
	return nil, nil
}

func CalculateResponse(privateKey any, challenge *Challenge) (*Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func VerifyChallengeResponse(publicKey any, challenge *Challenge, response *Response) error {
	_ = "STUB: not implemented"
	return nil
}

func GenerateRSASignatureChallenge() (*RSASignatureChallenge, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func CalculateRSASignatureResponse(privateKey *rsa.PrivateKey, challenge *RSASignatureChallenge) (*RSASignatureResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func VerifyRSASignatureResponse(publicKey *rsa.PublicKey, challenge *RSASignatureChallenge, response *RSASignatureResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func GenerateECDSASignatureChallenge() (*ECDSASignatureChallenge, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func CalculateECDSASignatureResponse(privateKey *ecdsa.PrivateKey, challenge *ECDSASignatureChallenge) (*ECDSASignatureResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func VerifyECDSASignatureResponse(publicKey *ecdsa.PublicKey, challenge *ECDSASignatureChallenge, response *ECDSASignatureResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func Fingerprint(cert *x509.Certificate) string { _ = "STUB: not implemented"; return "" }

//nolint: gosec // SHA1 use is according to specification

// MakeAgentID creates an agent ID from X.509 certificate data.
func MakeAgentID(td spiffeid.TrustDomain, agentPathTemplate *agentpathtemplate.Template, cert *x509.Certificate, svidPathTrimmed string, sanSelectors map[string]string) (spiffeid.ID, error) {
	_ = "STUB: not implemented"
	return *new(spiffeid.ID), nil
}

// SerialNumberHex returns a certificate serial number represented as lowercase hexadecimal with an even number of characters
func SerialNumberHex(serialNumber *big.Int) string { _ = "STUB: not implemented"; return "" }

// Append leading 0 in cases where hexadecimal representation is odd number of characters
// in order to be more consistent with other tooling that displays certificate serial numbers.

func generateNonce() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func combineNonces(challenge, response []byte) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// write the challenge and response and ignore errors since it won't fail
// writing to the digest
