// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: spire/common/plugin/plugin.proto

package plugin

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * Represents the plugin-specific configuration string.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * The configuration for the plugin.
	Configuration string `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// * Global configurations.
	GlobalConfig  *ConfigureRequest_GlobalConfig `protobuf:"bytes,2,opt,name=globalConfig,proto3" json:"globalConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ConfigureRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ConfigureRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ConfigureRequest) GetConfiguration() string { _ = "STUB: not implemented"; return "" }

func (x *ConfigureRequest) GetGlobalConfig() *ConfigureRequest_GlobalConfig {
	_ = "STUB: not implemented"
	return nil
}

// * Represents a list of configuration problems
// found in the configuration string.
type ConfigureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * A list of errors
	ErrorList     []string `protobuf:"bytes,1,rep,name=errorList,proto3" json:"errorList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *ConfigureResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*ConfigureResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ConfigureResponse) GetErrorList() []string { _ = "STUB: not implemented"; return nil }

// * Represents an empty request.
type GetPluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *GetPluginInfoRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*GetPluginInfoRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetPluginInfoRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

// * Represents the plugin metadata.
type GetPluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DateCreated   string                 `protobuf:"bytes,5,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	Company       string                 `protobuf:"bytes,9,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *GetPluginInfoResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*GetPluginInfoResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *GetPluginInfoResponse) GetName() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetCategory() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetType() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetDescription() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetDateCreated() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetLocation() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetVersion() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetAuthor() string { _ = "STUB: not implemented"; return "" }

func (x *GetPluginInfoResponse) GetCompany() string { _ = "STUB: not implemented"; return "" }

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServices  []string               `protobuf:"bytes,1,rep,name=host_services,json=hostServices,proto3" json:"host_services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *InitRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*InitRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *InitRequest) GetHostServices() []string { _ = "STUB: not implemented"; return nil }

type InitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PluginServices []string               `protobuf:"bytes,1,rep,name=plugin_services,json=pluginServices,proto3" json:"plugin_services,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *InitResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*InitResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *InitResponse) GetPluginServices() []string { _ = "STUB: not implemented"; return nil }

// * Global configuration nested type.
type ConfigureRequest_GlobalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trustDomain,proto3" json:"trustDomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest_GlobalConfig) Reset() { _ = "STUB: not implemented"; return }

func (x *ConfigureRequest_GlobalConfig) String() string { _ = "STUB: not implemented"; return "" }

func (*ConfigureRequest_GlobalConfig) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ConfigureRequest_GlobalConfig) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ConfigureRequest_GlobalConfig.ProtoReflect.Descriptor instead.
func (*ConfigureRequest_GlobalConfig) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ConfigureRequest_GlobalConfig) GetTrustDomain() string {
	_ = "STUB: not implemented"
	return ""
}

var File_spire_common_plugin_plugin_proto protoreflect.FileDescriptor

const file_spire_common_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	" spire/common/plugin/plugin.proto\x12\x13spire.common.plugin\"\xc2\x01\n" +
	"\x10ConfigureRequest\x12$\n" +
	"\rconfiguration\x18\x01 \x01(\tR\rconfiguration\x12V\n" +
	"\fglobalConfig\x18\x02 \x01(\v22.spire.common.plugin.ConfigureRequest.GlobalConfigR\fglobalConfig\x1a0\n" +
	"\fGlobalConfig\x12 \n" +
	"\vtrustDomain\x18\x01 \x01(\tR\vtrustDomain\"1\n" +
	"\x11ConfigureResponse\x12\x1c\n" +
	"\terrorList\x18\x01 \x03(\tR\terrorList\"\x16\n" +
	"\x14GetPluginInfoRequest\"\x87\x02\n" +
	"\x15GetPluginInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vdateCreated\x18\x05 \x01(\tR\vdateCreated\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\b \x01(\tR\x06author\x12\x18\n" +
	"\acompany\x18\t \x01(\tR\acompany\"2\n" +
	"\vInitRequest\x12#\n" +
	"\rhost_services\x18\x01 \x03(\tR\fhostServices\"7\n" +
	"\fInitResponse\x12'\n" +
	"\x0fplugin_services\x18\x01 \x03(\tR\x0epluginServices2Y\n" +
	"\n" +
	"PluginInit\x12K\n" +
	"\x04Init\x12 .spire.common.plugin.InitRequest\x1a!.spire.common.plugin.InitResponseB3Z1github.com/spiffe/spire/proto/spire/common/pluginb\x06proto3"

var (
	file_spire_common_plugin_plugin_proto_rawDescOnce sync.Once
	file_spire_common_plugin_plugin_proto_rawDescData []byte
)

func file_spire_common_plugin_plugin_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_spire_common_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_spire_common_plugin_plugin_proto_goTypes = []any{
	(*ConfigureRequest)(nil),              // 0: spire.common.plugin.ConfigureRequest
	(*ConfigureResponse)(nil),             // 1: spire.common.plugin.ConfigureResponse
	(*GetPluginInfoRequest)(nil),          // 2: spire.common.plugin.GetPluginInfoRequest
	(*GetPluginInfoResponse)(nil),         // 3: spire.common.plugin.GetPluginInfoResponse
	(*InitRequest)(nil),                   // 4: spire.common.plugin.InitRequest
	(*InitResponse)(nil),                  // 5: spire.common.plugin.InitResponse
	(*ConfigureRequest_GlobalConfig)(nil), // 6: spire.common.plugin.ConfigureRequest.GlobalConfig
}
var file_spire_common_plugin_plugin_proto_depIdxs = []int32{
	6, // 0: spire.common.plugin.ConfigureRequest.globalConfig:type_name -> spire.common.plugin.ConfigureRequest.GlobalConfig
	4, // 1: spire.common.plugin.PluginInit.Init:input_type -> spire.common.plugin.InitRequest
	5, // 2: spire.common.plugin.PluginInit.Init:output_type -> spire.common.plugin.InitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                       { file_spire_common_plugin_plugin_proto_init() }
func file_spire_common_plugin_plugin_proto_init() { _ = "STUB: not implemented"; return }
