// Code generated by protoc-gen-go-spire. DO NOT EDIT.

package plugin

import (
	pluginsdk "github.com/spiffe/spire-plugin-sdk/pluginsdk"
	grpc "google.golang.org/grpc"
)

func PluginInitPluginServer(server PluginInitServer) pluginsdk.PluginServer {
	_ = "STUB: not implemented"
	return *new(pluginsdk.PluginServer)
}

type pluginInitPluginServer struct {
	PluginInitServer
}

func (s pluginInitPluginServer) Type() string { _ = "STUB: not implemented"; return "" }

func (s pluginInitPluginServer) GRPCServiceName() string { _ = "STUB: not implemented"; return "" }

func (s pluginInitPluginServer) RegisterServer(server *grpc.Server) interface{} {
	_ = "STUB: not implemented"
	return nil
}

type PluginInitPluginClient struct {
	PluginInitClient
}

func (s PluginInitPluginClient) Type() string { _ = "STUB: not implemented"; return "" }

func (c *PluginInitPluginClient) IsInitialized() bool { _ = "STUB: not implemented"; return false }

func (c *PluginInitPluginClient) GRPCServiceName() string { _ = "STUB: not implemented"; return "" }

func (c *PluginInitPluginClient) InitClient(conn grpc.ClientConnInterface) interface{} {
	_ = "STUB: not implemented"
	return nil
}
