// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: spire/common/common.proto

package common

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * Represents an empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() { _ = "STUB: not implemented"; return }

func (x *Empty) String() string { _ = "STUB: not implemented"; return "" }

func (*Empty) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Empty) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// * A type which contains attestation data for specific platform.
type AttestationData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Type of attestation to perform.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// * The attestation data.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationData) Reset() { _ = "STUB: not implemented"; return }

func (x *AttestationData) String() string { _ = "STUB: not implemented"; return "" }

func (*AttestationData) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AttestationData) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AttestationData.ProtoReflect.Descriptor instead.
func (*AttestationData) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AttestationData) GetType() string { _ = "STUB: not implemented"; return "" }

func (x *AttestationData) GetData() []byte { _ = "STUB: not implemented"; return nil }

// * A type which describes the conditions under which a registration
// entry is matched.
type Selector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * A selector type represents the type of attestation used in attesting
	// the entity (Eg: AWS, K8).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// * The value to be attested.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() { _ = "STUB: not implemented"; return }

func (x *Selector) String() string { _ = "STUB: not implemented"; return "" }

func (*Selector) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Selector) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Selector) GetType() string { _ = "STUB: not implemented"; return "" }

func (x *Selector) GetValue() string { _ = "STUB: not implemented"; return "" }

// * Represents a type with a list of Selector.
type Selectors struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * A list of Selector.
	Entries       []*Selector `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selectors) Reset() { _ = "STUB: not implemented"; return }

func (x *Selectors) String() string { _ = "STUB: not implemented"; return "" }

func (*Selectors) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Selectors) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Selectors.ProtoReflect.Descriptor instead.
func (*Selectors) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Selectors) GetEntries() []*Selector { _ = "STUB: not implemented"; return nil }

// Represents an attested SPIRE agent
type AttestedNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node SPIFFE ID
	SpiffeId string `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Attestation data type
	AttestationDataType string `protobuf:"bytes,2,opt,name=attestation_data_type,json=attestationDataType,proto3" json:"attestation_data_type,omitempty"`
	// Node certificate serial number
	CertSerialNumber string `protobuf:"bytes,3,opt,name=cert_serial_number,json=certSerialNumber,proto3" json:"cert_serial_number,omitempty"`
	// Node certificate not_after (seconds since unix epoch)
	CertNotAfter int64 `protobuf:"varint,4,opt,name=cert_not_after,json=certNotAfter,proto3" json:"cert_not_after,omitempty"`
	// Node certificate serial number
	NewCertSerialNumber string `protobuf:"bytes,5,opt,name=new_cert_serial_number,json=newCertSerialNumber,proto3" json:"new_cert_serial_number,omitempty"`
	// Node certificate not_after (seconds since unix epoch)
	NewCertNotAfter int64 `protobuf:"varint,6,opt,name=new_cert_not_after,json=newCertNotAfter,proto3" json:"new_cert_not_after,omitempty"`
	// Node selectors
	Selectors []*Selector `protobuf:"bytes,7,rep,name=selectors,proto3" json:"selectors,omitempty"`
	// CanReattest field (can the attestation safely be deleted and recreated automatically)
	CanReattest bool `protobuf:"varint,8,opt,name=can_reattest,json=canReattest,proto3" json:"can_reattest,omitempty"`
	// AgentVersion is the version of the SPIRE agent
	AgentVersion  string `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedNode) Reset() { _ = "STUB: not implemented"; return }

func (x *AttestedNode) String() string { _ = "STUB: not implemented"; return "" }

func (*AttestedNode) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AttestedNode) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AttestedNode.ProtoReflect.Descriptor instead.
func (*AttestedNode) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AttestedNode) GetSpiffeId() string { _ = "STUB: not implemented"; return "" }

func (x *AttestedNode) GetAttestationDataType() string { _ = "STUB: not implemented"; return "" }

func (x *AttestedNode) GetCertSerialNumber() string { _ = "STUB: not implemented"; return "" }

func (x *AttestedNode) GetCertNotAfter() int64 { _ = "STUB: not implemented"; return 0 }

func (x *AttestedNode) GetNewCertSerialNumber() string { _ = "STUB: not implemented"; return "" }

func (x *AttestedNode) GetNewCertNotAfter() int64 { _ = "STUB: not implemented"; return 0 }

func (x *AttestedNode) GetSelectors() []*Selector { _ = "STUB: not implemented"; return nil }

func (x *AttestedNode) GetCanReattest() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNode) GetAgentVersion() string { _ = "STUB: not implemented"; return "" }

// * This is a curated record that the Server uses to set up and
// manage the various registered nodes and workloads that are controlled by it.
type RegistrationEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * A list of selectors.
	Selectors []*Selector `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	// * The SPIFFE ID of an entity that is authorized to attest the validity
	// of a selector
	ParentId string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// * The SPIFFE ID is a structured string used to identify a resource or
	// caller. It is defined as a URI comprising a “trust domain” and an
	// associated path.
	SpiffeId string `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// * Time to live for X509-SVIDs generated from this entry. Was previously called 'ttl'.
	X509SvidTtl int32 `protobuf:"varint,4,opt,name=x509_svid_ttl,json=x509SvidTtl,proto3" json:"x509_svid_ttl,omitempty"`
	// * A list of federated trust domain SPIFFE IDs.
	FederatesWith []string `protobuf:"bytes,5,rep,name=federates_with,json=federatesWith,proto3" json:"federates_with,omitempty"`
	// * Entry ID
	EntryId string `protobuf:"bytes,6,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// * whether the workload is an admin workload. Admin workloads
	// can use their SVID's to authenticate with the Server APIs, for
	// example.
	Admin bool `protobuf:"varint,7,opt,name=admin,proto3" json:"admin,omitempty"`
	// * To enable signing CA CSR in upstream spire server
	Downstream bool `protobuf:"varint,8,opt,name=downstream,proto3" json:"downstream,omitempty"`
	// * Expiration of this entry, in seconds from epoch
	EntryExpiry int64 `protobuf:"varint,9,opt,name=entryExpiry,proto3" json:"entryExpiry,omitempty"`
	// * DNS entries
	DnsNames []string `protobuf:"bytes,10,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	// * Revision number is bumped every time the entry is updated
	RevisionNumber int64 `protobuf:"varint,11,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	// * Determines if the issued SVID must be stored through an SVIDStore plugin
	StoreSvid bool `protobuf:"varint,12,opt,name=store_svid,json=storeSvid,proto3" json:"store_svid,omitempty"`
	// * Time to live for JWT-SVIDs generated from this entry, if set will override ttl field.
	JwtSvidTtl int32 `protobuf:"varint,13,opt,name=jwt_svid_ttl,json=jwtSvidTtl,proto3" json:"jwt_svid_ttl,omitempty"`
	// * An operator-specified string used to provide guidance on how this
	// identity should be used by a workload when more than one SVID is returned.
	Hint string `protobuf:"bytes,14,opt,name=hint,proto3" json:"hint,omitempty"`
	// * Time of creation, in seconds from epoch
	CreatedAt            int64                                   `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AdditionalAttributes *RegistrationEntry_AdditionalAttributes `protobuf:"bytes,16,opt,name=additional_attributes,json=additionalAttributes,proto3,oneof" json:"additional_attributes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegistrationEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*RegistrationEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RegistrationEntry.ProtoReflect.Descriptor instead.
func (*RegistrationEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RegistrationEntry) GetSelectors() []*Selector { _ = "STUB: not implemented"; return nil }

func (x *RegistrationEntry) GetParentId() string { _ = "STUB: not implemented"; return "" }

func (x *RegistrationEntry) GetSpiffeId() string { _ = "STUB: not implemented"; return "" }

func (x *RegistrationEntry) GetX509SvidTtl() int32 { _ = "STUB: not implemented"; return 0 }

func (x *RegistrationEntry) GetFederatesWith() []string { _ = "STUB: not implemented"; return nil }

func (x *RegistrationEntry) GetEntryId() string { _ = "STUB: not implemented"; return "" }

func (x *RegistrationEntry) GetAdmin() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntry) GetDownstream() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntry) GetEntryExpiry() int64 { _ = "STUB: not implemented"; return 0 }

func (x *RegistrationEntry) GetDnsNames() []string { _ = "STUB: not implemented"; return nil }

func (x *RegistrationEntry) GetRevisionNumber() int64 { _ = "STUB: not implemented"; return 0 }

func (x *RegistrationEntry) GetStoreSvid() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntry) GetJwtSvidTtl() int32 { _ = "STUB: not implemented"; return 0 }

func (x *RegistrationEntry) GetHint() string { _ = "STUB: not implemented"; return "" }

func (x *RegistrationEntry) GetCreatedAt() int64 { _ = "STUB: not implemented"; return 0 }

func (x *RegistrationEntry) GetAdditionalAttributes() *RegistrationEntry_AdditionalAttributes {
	_ = "STUB: not implemented"
	return nil
}

// * The RegistrationEntryMask is used to update only selected fields of the RegistrationEntry
type RegistrationEntryMask struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Selectors            bool                   `protobuf:"varint,1,opt,name=selectors,proto3" json:"selectors,omitempty"`
	ParentId             bool                   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SpiffeId             bool                   `protobuf:"varint,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	X509SvidTtl          bool                   `protobuf:"varint,4,opt,name=x509_svid_ttl,json=x509SvidTtl,proto3" json:"x509_svid_ttl,omitempty"`
	FederatesWith        bool                   `protobuf:"varint,5,opt,name=federates_with,json=federatesWith,proto3" json:"federates_with,omitempty"`
	EntryId              bool                   `protobuf:"varint,6,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Admin                bool                   `protobuf:"varint,7,opt,name=admin,proto3" json:"admin,omitempty"`
	Downstream           bool                   `protobuf:"varint,8,opt,name=downstream,proto3" json:"downstream,omitempty"`
	EntryExpiry          bool                   `protobuf:"varint,9,opt,name=entryExpiry,proto3" json:"entryExpiry,omitempty"`
	DnsNames             bool                   `protobuf:"varint,10,opt,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	StoreSvid            bool                   `protobuf:"varint,11,opt,name=store_svid,json=storeSvid,proto3" json:"store_svid,omitempty"`
	JwtSvidTtl           bool                   `protobuf:"varint,12,opt,name=jwt_svid_ttl,json=jwtSvidTtl,proto3" json:"jwt_svid_ttl,omitempty"`
	Hint                 bool                   `protobuf:"varint,13,opt,name=hint,proto3" json:"hint,omitempty"`
	AdditionalAttributes bool                   `protobuf:"varint,14,opt,name=additional_attributes,json=additionalAttributes,proto3" json:"additional_attributes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegistrationEntryMask) Reset() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntryMask) String() string { _ = "STUB: not implemented"; return "" }

func (*RegistrationEntryMask) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntryMask) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RegistrationEntryMask.ProtoReflect.Descriptor instead.
func (*RegistrationEntryMask) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *RegistrationEntryMask) GetSelectors() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetParentId() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetSpiffeId() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetX509SvidTtl() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetFederatesWith() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetEntryId() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetAdmin() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetDownstream() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetEntryExpiry() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetDnsNames() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetStoreSvid() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetJwtSvidTtl() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetHint() bool { _ = "STUB: not implemented"; return false }

func (x *RegistrationEntryMask) GetAdditionalAttributes() bool {
	_ = "STUB: not implemented"
	return false
}

// * A list of registration entries.
type RegistrationEntries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * A list of RegistrationEntry.
	Entries       []*RegistrationEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationEntries) Reset() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntries) String() string { _ = "STUB: not implemented"; return "" }

func (*RegistrationEntries) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntries) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RegistrationEntries.ProtoReflect.Descriptor instead.
func (*RegistrationEntries) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *RegistrationEntries) GetEntries() []*RegistrationEntry {
	_ = "STUB: not implemented"
	return nil
}

// * Certificate represents a ASN.1/DER encoded X509 certificate
type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DerBytes      []byte                 `protobuf:"bytes,1,opt,name=der_bytes,json=derBytes,proto3" json:"der_bytes,omitempty"`
	TaintedKey    bool                   `protobuf:"varint,2,opt,name=tainted_key,json=taintedKey,proto3" json:"tainted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() { _ = "STUB: not implemented"; return }

func (x *Certificate) String() string { _ = "STUB: not implemented"; return "" }

func (*Certificate) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Certificate) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Certificate) GetDerBytes() []byte { _ = "STUB: not implemented"; return nil }

func (x *Certificate) GetTaintedKey() bool { _ = "STUB: not implemented"; return false }

// * PublicKey represents a PKIX encoded public key
type PublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * PKIX encoded key data
	PkixBytes []byte `protobuf:"bytes,1,opt,name=pkix_bytes,json=pkixBytes,proto3" json:"pkix_bytes,omitempty"`
	// * key identifier
	Kid string `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
	// * not after (seconds since unix epoch, 0 means "never expires")
	NotAfter int64 `protobuf:"varint,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// * whether the key is tainted
	TaintedKey    bool `protobuf:"varint,4,opt,name=tainted_key,json=taintedKey,proto3" json:"tainted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() { _ = "STUB: not implemented"; return }

func (x *PublicKey) String() string { _ = "STUB: not implemented"; return "" }

func (*PublicKey) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PublicKey) GetPkixBytes() []byte { _ = "STUB: not implemented"; return nil }

func (x *PublicKey) GetKid() string { _ = "STUB: not implemented"; return "" }

func (x *PublicKey) GetNotAfter() int64 { _ = "STUB: not implemented"; return 0 }

func (x *PublicKey) GetTaintedKey() bool { _ = "STUB: not implemented"; return false }

type Bundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * the SPIFFE ID of the trust domain the bundle belongs to
	TrustDomainId string `protobuf:"bytes,1,opt,name=trust_domain_id,json=trustDomainId,proto3" json:"trust_domain_id,omitempty"`
	// * list of root CA certificates
	RootCas []*Certificate `protobuf:"bytes,2,rep,name=root_cas,json=rootCas,proto3" json:"root_cas,omitempty"`
	// * list of JWT signing keys
	JwtSigningKeys []*PublicKey `protobuf:"bytes,3,rep,name=jwt_signing_keys,json=jwtSigningKeys,proto3" json:"jwt_signing_keys,omitempty"`
	// * refresh hint is a hint, in seconds, on how often a bundle consumer
	// should poll for bundle updates
	RefreshHint int64 `protobuf:"varint,4,opt,name=refresh_hint,json=refreshHint,proto3" json:"refresh_hint,omitempty"`
	// * sequence number is a monotonically increasing number that is
	// incremented every time the bundle is updated
	SequenceNumber uint64 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// * list of WIT signing keys
	WitSigningKeys []*PublicKey `protobuf:"bytes,6,rep,name=wit_signing_keys,json=witSigningKeys,proto3" json:"wit_signing_keys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Bundle) Reset() { _ = "STUB: not implemented"; return }

func (x *Bundle) String() string { _ = "STUB: not implemented"; return "" }

func (*Bundle) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Bundle) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Bundle) GetTrustDomainId() string { _ = "STUB: not implemented"; return "" }

func (x *Bundle) GetRootCas() []*Certificate { _ = "STUB: not implemented"; return nil }

func (x *Bundle) GetJwtSigningKeys() []*PublicKey { _ = "STUB: not implemented"; return nil }

func (x *Bundle) GetRefreshHint() int64 { _ = "STUB: not implemented"; return 0 }

func (x *Bundle) GetSequenceNumber() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Bundle) GetWitSigningKeys() []*PublicKey { _ = "STUB: not implemented"; return nil }

type BundleMask struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootCas         bool                   `protobuf:"varint,1,opt,name=root_cas,json=rootCas,proto3" json:"root_cas,omitempty"`
	JwtSigningKeys  bool                   `protobuf:"varint,2,opt,name=jwt_signing_keys,json=jwtSigningKeys,proto3" json:"jwt_signing_keys,omitempty"`
	RefreshHint     bool                   `protobuf:"varint,3,opt,name=refresh_hint,json=refreshHint,proto3" json:"refresh_hint,omitempty"`
	SequenceNumber  bool                   `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	X509TaintedKeys bool                   `protobuf:"varint,5,opt,name=x509_tainted_keys,json=x509TaintedKeys,proto3" json:"x509_tainted_keys,omitempty"`
	WitSigningKeys  bool                   `protobuf:"varint,6,opt,name=wit_signing_keys,json=witSigningKeys,proto3" json:"wit_signing_keys,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BundleMask) Reset() { _ = "STUB: not implemented"; return }

func (x *BundleMask) String() string { _ = "STUB: not implemented"; return "" }

func (*BundleMask) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *BundleMask) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use BundleMask.ProtoReflect.Descriptor instead.
func (*BundleMask) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *BundleMask) GetRootCas() bool { _ = "STUB: not implemented"; return false }

func (x *BundleMask) GetJwtSigningKeys() bool { _ = "STUB: not implemented"; return false }

func (x *BundleMask) GetRefreshHint() bool { _ = "STUB: not implemented"; return false }

func (x *BundleMask) GetSequenceNumber() bool { _ = "STUB: not implemented"; return false }

func (x *BundleMask) GetX509TaintedKeys() bool { _ = "STUB: not implemented"; return false }

func (x *BundleMask) GetWitSigningKeys() bool { _ = "STUB: not implemented"; return false }

type AttestedNodeMask struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AttestationDataType bool                   `protobuf:"varint,1,opt,name=attestation_data_type,json=attestationDataType,proto3" json:"attestation_data_type,omitempty"`
	CertSerialNumber    bool                   `protobuf:"varint,2,opt,name=cert_serial_number,json=certSerialNumber,proto3" json:"cert_serial_number,omitempty"`
	CertNotAfter        bool                   `protobuf:"varint,3,opt,name=cert_not_after,json=certNotAfter,proto3" json:"cert_not_after,omitempty"`
	NewCertSerialNumber bool                   `protobuf:"varint,4,opt,name=new_cert_serial_number,json=newCertSerialNumber,proto3" json:"new_cert_serial_number,omitempty"`
	NewCertNotAfter     bool                   `protobuf:"varint,5,opt,name=new_cert_not_after,json=newCertNotAfter,proto3" json:"new_cert_not_after,omitempty"`
	CanReattest         bool                   `protobuf:"varint,6,opt,name=can_reattest,json=canReattest,proto3" json:"can_reattest,omitempty"`
	AgentVersion        bool                   `protobuf:"varint,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttestedNodeMask) Reset() { _ = "STUB: not implemented"; return }

func (x *AttestedNodeMask) String() string { _ = "STUB: not implemented"; return "" }

func (*AttestedNodeMask) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AttestedNodeMask) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AttestedNodeMask.ProtoReflect.Descriptor instead.
func (*AttestedNodeMask) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AttestedNodeMask) GetAttestationDataType() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNodeMask) GetCertSerialNumber() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNodeMask) GetCertNotAfter() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNodeMask) GetNewCertSerialNumber() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNodeMask) GetNewCertNotAfter() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNodeMask) GetCanReattest() bool { _ = "STUB: not implemented"; return false }

func (x *AttestedNodeMask) GetAgentVersion() bool { _ = "STUB: not implemented"; return false }

// * This nested message is reserved to contain a number of optional fields
// controlling the various aspects of the agent's behaviour with respect to a
// given registration entry. It serves to enable introducing and testing out new
// tunables, without having to modify the datastore schema. Over time, some of
// the fields contained therein may be considered eligible for their dedicated
// attributes in the datastore.
type RegistrationEntry_AdditionalAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Flag indicating whether the agent should prefetch and cache X509 SVID.
	// Can be set to `true` if the workload is unlikely to request an X509 SVID.
	// This is meant to prevent unnecessary effort spent on generating SVIDs of types,
	// which are unlikely to be needed.
	DisableX509SvidPrefetch bool `protobuf:"varint,1,opt,name=disable_x509_svid_prefetch,json=disableX509SvidPrefetch,proto3" json:"disable_x509_svid_prefetch,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegistrationEntry_AdditionalAttributes) Reset() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntry_AdditionalAttributes) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*RegistrationEntry_AdditionalAttributes) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RegistrationEntry_AdditionalAttributes) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RegistrationEntry_AdditionalAttributes.ProtoReflect.Descriptor instead.
func (*RegistrationEntry_AdditionalAttributes) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *RegistrationEntry_AdditionalAttributes) GetDisableX509SvidPrefetch() bool {
	_ = "STUB: not implemented"
	return false
}

var File_spire_common_common_proto protoreflect.FileDescriptor

const file_spire_common_common_proto_rawDesc = "" +
	"\n" +
	"\x19spire/common/common.proto\x12\fspire.common\"\a\n" +
	"\x05Empty\"9\n" +
	"\x0fAttestationData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"4\n" +
	"\bSelector\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\tSelectors\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.spire.common.SelectorR\aentries\"\x93\x03\n" +
	"\fAttestedNode\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x122\n" +
	"\x15attestation_data_type\x18\x02 \x01(\tR\x13attestationDataType\x12,\n" +
	"\x12cert_serial_number\x18\x03 \x01(\tR\x10certSerialNumber\x12$\n" +
	"\x0ecert_not_after\x18\x04 \x01(\x03R\fcertNotAfter\x123\n" +
	"\x16new_cert_serial_number\x18\x05 \x01(\tR\x13newCertSerialNumber\x12+\n" +
	"\x12new_cert_not_after\x18\x06 \x01(\x03R\x0fnewCertNotAfter\x124\n" +
	"\tselectors\x18\a \x03(\v2\x16.spire.common.SelectorR\tselectors\x12!\n" +
	"\fcan_reattest\x18\b \x01(\bR\vcanReattest\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\"\xda\x05\n" +
	"\x11RegistrationEntry\x124\n" +
	"\tselectors\x18\x01 \x03(\v2\x16.spire.common.SelectorR\tselectors\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\x12\"\n" +
	"\rx509_svid_ttl\x18\x04 \x01(\x05R\vx509SvidTtl\x12%\n" +
	"\x0efederates_with\x18\x05 \x03(\tR\rfederatesWith\x12\x19\n" +
	"\bentry_id\x18\x06 \x01(\tR\aentryId\x12\x14\n" +
	"\x05admin\x18\a \x01(\bR\x05admin\x12\x1e\n" +
	"\n" +
	"downstream\x18\b \x01(\bR\n" +
	"downstream\x12 \n" +
	"\ventryExpiry\x18\t \x01(\x03R\ventryExpiry\x12\x1b\n" +
	"\tdns_names\x18\n" +
	" \x03(\tR\bdnsNames\x12'\n" +
	"\x0frevision_number\x18\v \x01(\x03R\x0erevisionNumber\x12\x1d\n" +
	"\n" +
	"store_svid\x18\f \x01(\bR\tstoreSvid\x12 \n" +
	"\fjwt_svid_ttl\x18\r \x01(\x05R\n" +
	"jwtSvidTtl\x12\x12\n" +
	"\x04hint\x18\x0e \x01(\tR\x04hint\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12n\n" +
	"\x15additional_attributes\x18\x10 \x01(\v24.spire.common.RegistrationEntry.AdditionalAttributesH\x00R\x14additionalAttributes\x88\x01\x01\x1aS\n" +
	"\x14AdditionalAttributes\x12;\n" +
	"\x1adisable_x509_svid_prefetch\x18\x01 \x01(\bR\x17disableX509SvidPrefetchB\x18\n" +
	"\x16_additional_attributes\"\xd4\x03\n" +
	"\x15RegistrationEntryMask\x12\x1c\n" +
	"\tselectors\x18\x01 \x01(\bR\tselectors\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\bR\bparentId\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\bR\bspiffeId\x12\"\n" +
	"\rx509_svid_ttl\x18\x04 \x01(\bR\vx509SvidTtl\x12%\n" +
	"\x0efederates_with\x18\x05 \x01(\bR\rfederatesWith\x12\x19\n" +
	"\bentry_id\x18\x06 \x01(\bR\aentryId\x12\x14\n" +
	"\x05admin\x18\a \x01(\bR\x05admin\x12\x1e\n" +
	"\n" +
	"downstream\x18\b \x01(\bR\n" +
	"downstream\x12 \n" +
	"\ventryExpiry\x18\t \x01(\bR\ventryExpiry\x12\x1b\n" +
	"\tdns_names\x18\n" +
	" \x01(\bR\bdnsNames\x12\x1d\n" +
	"\n" +
	"store_svid\x18\v \x01(\bR\tstoreSvid\x12 \n" +
	"\fjwt_svid_ttl\x18\f \x01(\bR\n" +
	"jwtSvidTtl\x12\x12\n" +
	"\x04hint\x18\r \x01(\bR\x04hint\x123\n" +
	"\x15additional_attributes\x18\x0e \x01(\bR\x14additionalAttributes\"P\n" +
	"\x13RegistrationEntries\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.spire.common.RegistrationEntryR\aentries\"K\n" +
	"\vCertificate\x12\x1b\n" +
	"\tder_bytes\x18\x01 \x01(\fR\bderBytes\x12\x1f\n" +
	"\vtainted_key\x18\x02 \x01(\bR\n" +
	"taintedKey\"z\n" +
	"\tPublicKey\x12\x1d\n" +
	"\n" +
	"pkix_bytes\x18\x01 \x01(\fR\tpkixBytes\x12\x10\n" +
	"\x03kid\x18\x02 \x01(\tR\x03kid\x12\x1b\n" +
	"\tnot_after\x18\x03 \x01(\x03R\bnotAfter\x12\x1f\n" +
	"\vtainted_key\x18\x04 \x01(\bR\n" +
	"taintedKey\"\xb8\x02\n" +
	"\x06Bundle\x12&\n" +
	"\x0ftrust_domain_id\x18\x01 \x01(\tR\rtrustDomainId\x124\n" +
	"\broot_cas\x18\x02 \x03(\v2\x19.spire.common.CertificateR\arootCas\x12A\n" +
	"\x10jwt_signing_keys\x18\x03 \x03(\v2\x17.spire.common.PublicKeyR\x0ejwtSigningKeys\x12!\n" +
	"\frefresh_hint\x18\x04 \x01(\x03R\vrefreshHint\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x04R\x0esequenceNumber\x12A\n" +
	"\x10wit_signing_keys\x18\x06 \x03(\v2\x17.spire.common.PublicKeyR\x0ewitSigningKeys\"\xf3\x01\n" +
	"\n" +
	"BundleMask\x12\x19\n" +
	"\broot_cas\x18\x01 \x01(\bR\arootCas\x12(\n" +
	"\x10jwt_signing_keys\x18\x02 \x01(\bR\x0ejwtSigningKeys\x12!\n" +
	"\frefresh_hint\x18\x03 \x01(\bR\vrefreshHint\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\bR\x0esequenceNumber\x12*\n" +
	"\x11x509_tainted_keys\x18\x05 \x01(\bR\x0fx509TaintedKeys\x12(\n" +
	"\x10wit_signing_keys\x18\x06 \x01(\bR\x0ewitSigningKeys\"\xc4\x02\n" +
	"\x10AttestedNodeMask\x122\n" +
	"\x15attestation_data_type\x18\x01 \x01(\bR\x13attestationDataType\x12,\n" +
	"\x12cert_serial_number\x18\x02 \x01(\bR\x10certSerialNumber\x12$\n" +
	"\x0ecert_not_after\x18\x03 \x01(\bR\fcertNotAfter\x123\n" +
	"\x16new_cert_serial_number\x18\x04 \x01(\bR\x13newCertSerialNumber\x12+\n" +
	"\x12new_cert_not_after\x18\x05 \x01(\bR\x0fnewCertNotAfter\x12!\n" +
	"\fcan_reattest\x18\x06 \x01(\bR\vcanReattest\x12#\n" +
	"\ragent_version\x18\a \x01(\bR\fagentVersionB,Z*github.com/spiffe/spire/proto/spire/commonb\x06proto3"

var (
	file_spire_common_common_proto_rawDescOnce sync.Once
	file_spire_common_common_proto_rawDescData []byte
)

func file_spire_common_common_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_spire_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_spire_common_common_proto_goTypes = []any{
	(*Empty)(nil),                                  // 0: spire.common.Empty
	(*AttestationData)(nil),                        // 1: spire.common.AttestationData
	(*Selector)(nil),                               // 2: spire.common.Selector
	(*Selectors)(nil),                              // 3: spire.common.Selectors
	(*AttestedNode)(nil),                           // 4: spire.common.AttestedNode
	(*RegistrationEntry)(nil),                      // 5: spire.common.RegistrationEntry
	(*RegistrationEntryMask)(nil),                  // 6: spire.common.RegistrationEntryMask
	(*RegistrationEntries)(nil),                    // 7: spire.common.RegistrationEntries
	(*Certificate)(nil),                            // 8: spire.common.Certificate
	(*PublicKey)(nil),                              // 9: spire.common.PublicKey
	(*Bundle)(nil),                                 // 10: spire.common.Bundle
	(*BundleMask)(nil),                             // 11: spire.common.BundleMask
	(*AttestedNodeMask)(nil),                       // 12: spire.common.AttestedNodeMask
	(*RegistrationEntry_AdditionalAttributes)(nil), // 13: spire.common.RegistrationEntry.AdditionalAttributes
}
var file_spire_common_common_proto_depIdxs = []int32{
	2,  // 0: spire.common.Selectors.entries:type_name -> spire.common.Selector
	2,  // 1: spire.common.AttestedNode.selectors:type_name -> spire.common.Selector
	2,  // 2: spire.common.RegistrationEntry.selectors:type_name -> spire.common.Selector
	13, // 3: spire.common.RegistrationEntry.additional_attributes:type_name -> spire.common.RegistrationEntry.AdditionalAttributes
	5,  // 4: spire.common.RegistrationEntries.entries:type_name -> spire.common.RegistrationEntry
	8,  // 5: spire.common.Bundle.root_cas:type_name -> spire.common.Certificate
	9,  // 6: spire.common.Bundle.jwt_signing_keys:type_name -> spire.common.PublicKey
	9,  // 7: spire.common.Bundle.wit_signing_keys:type_name -> spire.common.PublicKey
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init()                                { file_spire_common_common_proto_init() }
func file_spire_common_common_proto_init() { _ = "STUB: not implemented"; return }
