//go:build !darwin

package tpmsimulator

import (
	"crypto/rsa"
	"crypto/x509"
	"io"
	"time"

	"github.com/google/go-tpm-tools/simulator"
	"github.com/google/go-tpm/legacy/tpm2"
)

var ErrUsingClosedSimulator = simulator.ErrUsingClosedSimulator

type TPMSimulator struct {
	*simulator.Simulator
	ekRoot                       *x509.Certificate
	ownerHierarchyPassword       string
	endorsementHierarchyPassword string
}
type Credential struct {
	Certificate   *x509.Certificate
	Intermediates []*x509.Certificate
	PrivateBlob   []byte
	PublicBlob    []byte
}

type ProvisioningAuthority struct {
	RootCert         *x509.Certificate
	RootKey          *rsa.PrivateKey
	IntermediateCert *x509.Certificate
	IntermediateKey  *rsa.PrivateKey
}

type ProvisioningConf struct {
	NoIntermediates bool
	RootCertificate *x509.Certificate
	RootKey         *rsa.PrivateKey
}

type KeyType int

const (
	RSA KeyType = iota
	ECC
)

// The "never expires" timestamp from RFC5280
var neverExpires = time.Date(9999, 12, 31, 23, 59, 59, 0, time.UTC)

// DevID key template attributes according to TPM 2.0 Keys for device identity
// and attestation (section 7.3.4.1)
var flagDevIDKeyDefault = tpm2.FlagSign |
	tpm2.FlagFixedTPM |
	tpm2.FlagFixedParent |
	tpm2.FlagSensitiveDataOrigin |
	tpm2.FlagUserWithAuth

// New creates a new TPM simulator and sets an RSA endorsement certificate.
func New(endorsementHierarchyPassword, ownerHierarchyPassword string) (*TPMSimulator, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewProvisioningCA creates a new provisioning authority to issue DevIDs
// certificate. If root certificate and key are not provided, a new, self-signed
// certificate and key are generated.
func NewProvisioningCA(c *ProvisioningConf) (*ProvisioningAuthority, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Chain returns the leaf and intermediate certificates in DER format
func (c *Credential) Chain() [][]byte { _ = "STUB: not implemented"; return nil }

// ChainPem returns the leaf and intermediate certificates in PEM format
func (c *Credential) ChainPem() []byte { _ = "STUB: not implemented"; return nil }

func (s *TPMSimulator) OpenTPM(path ...string) (io.ReadWriteCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadWriteCloser), nil
}

// GenerateDevID generates a new DevID credential using the given provisioning
// authority and key type.
// DevIDs generated using this function are for test only. There is no guarantee
// that the identities generated by this method are compliant with the TCG/IEEE
// specification.
func (s *TPMSimulator) GenerateDevID(p *ProvisioningAuthority, keyType KeyType, keyPassword string) (*Credential, error) {
	_ = "STUB: not implemented"
	// Create key in TPM according to the given key type
	return nil, nil
}

// Decode public blob returned by TPM to get the public key

// Mint DevID certificate

// Create DevID credential

// GetEKRoot returns the manufacturer CA used to sign the endorsement certificate
func (s *TPMSimulator) GetEKRoot() *x509.Certificate { _ = "STUB: not implemented"; return nil }

func (s *TPMSimulator) SetEndorsementCertificate(ekCert []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *TPMSimulator) createEndorsementCertificate() (*x509.Certificate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// createOrdinaryKey creates an ordinary TPM key of the type keyType under
// the owner hierarchy
func (s *TPMSimulator) createOrdinaryKey(keyType KeyType, parentKeyPassword, keyPassword string) ([]byte, []byte, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

func (p *ProvisioningAuthority) issueCertificate(publicKey any) (*x509.Certificate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func createRootCertificate(key *rsa.PrivateKey, tmpl *x509.Certificate) (*x509.Certificate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func createCertificate(key any, tmpl *x509.Certificate, parentKey *rsa.PrivateKey, parent *x509.Certificate) (*x509.Certificate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func generateRSAKey() (*rsa.PrivateKey, error) { _ = "STUB: not implemented"; return nil, nil }

func defaultDevIDTemplateRSA() tpm2.Public { _ = "STUB: not implemented"; return *new(tpm2.Public) }

func defaultDevIDTemplateECC() tpm2.Public { _ = "STUB: not implemented"; return *new(tpm2.Public) }
