// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: private/server/journal/journal.proto

package journal

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	// Status is unknown.
	Status_UNKNOWN Status = 0
	// This holds a new authority that was prepared for future uses.
	Status_PREPARED Status = 2
	// This holds the active authority that is currently being used for
	// signing operations.
	Status_ACTIVE Status = 3
	// This holds an old authority that is no longer used.
	Status_OLD Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		2: "PREPARED",
		3: "ACTIVE",
		4: "OLD",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"PREPARED": 2,
		"ACTIVE":   3,
		"OLD":      4,
	}
)

func (x Status) Enum() *Status { _ = "STUB: not implemented"; return nil }

func (x Status) String() string { _ = "STUB: not implemented"; return "" }

func (Status) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Status) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Status) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type X509CAEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which X509 CA slot this entry occupied.
	SlotId string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// When the CA was issued (unix epoch in seconds)
	IssuedAt int64 `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// DER encoded CA certificate
	Certificate []byte `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// DER encoded upstream CA chain. See the X509CA struct for details.
	UpstreamChain [][]byte `protobuf:"bytes,4,rep,name=upstream_chain,json=upstreamChain,proto3" json:"upstream_chain,omitempty"`
	// The entry status
	Status Status `protobuf:"varint,5,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	// The X.509 Subject Key Identifier (SKID)
	AuthorityId string `protobuf:"bytes,6,opt,name=authority_id,json=authorityId,proto3" json:"authority_id,omitempty"`
	// When the CA expires (unix epoch in seconds)
	NotAfter int64 `protobuf:"varint,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// The X.509 Authority Subject Key Identifier (SKID)
	UpstreamAuthorityId string `protobuf:"bytes,8,opt,name=upstream_authority_id,json=upstreamAuthorityId,proto3" json:"upstream_authority_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *X509CAEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *X509CAEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*X509CAEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *X509CAEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use X509CAEntry.ProtoReflect.Descriptor instead.
func (*X509CAEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *X509CAEntry) GetSlotId() string { _ = "STUB: not implemented"; return "" }

func (x *X509CAEntry) GetIssuedAt() int64 { _ = "STUB: not implemented"; return 0 }

func (x *X509CAEntry) GetCertificate() []byte { _ = "STUB: not implemented"; return nil }

func (x *X509CAEntry) GetUpstreamChain() [][]byte { _ = "STUB: not implemented"; return nil }

func (x *X509CAEntry) GetStatus() Status { _ = "STUB: not implemented"; return *new(Status) }

func (x *X509CAEntry) GetAuthorityId() string { _ = "STUB: not implemented"; return "" }

func (x *X509CAEntry) GetNotAfter() int64 { _ = "STUB: not implemented"; return 0 }

func (x *X509CAEntry) GetUpstreamAuthorityId() string { _ = "STUB: not implemented"; return "" }

type JWTKeyEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which JWT Key slot this entry occupied.
	SlotId string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// When the key was issued (unix epoch in seconds)
	IssuedAt int64 `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// When the key expires unix epoch in seconds)
	NotAfter int64 `protobuf:"varint,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// JWT key id (i.e. "kid" claim)
	Kid string `protobuf:"bytes,4,opt,name=kid,proto3" json:"kid,omitempty"`
	// PKIX encoded public key
	PublicKey []byte `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The entry status
	Status Status `protobuf:"varint,6,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	// The JWT key ID
	AuthorityId   string `protobuf:"bytes,7,opt,name=authority_id,json=authorityId,proto3" json:"authority_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTKeyEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *JWTKeyEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*JWTKeyEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *JWTKeyEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use JWTKeyEntry.ProtoReflect.Descriptor instead.
func (*JWTKeyEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *JWTKeyEntry) GetSlotId() string { _ = "STUB: not implemented"; return "" }

func (x *JWTKeyEntry) GetIssuedAt() int64 { _ = "STUB: not implemented"; return 0 }

func (x *JWTKeyEntry) GetNotAfter() int64 { _ = "STUB: not implemented"; return 0 }

func (x *JWTKeyEntry) GetKid() string { _ = "STUB: not implemented"; return "" }

func (x *JWTKeyEntry) GetPublicKey() []byte { _ = "STUB: not implemented"; return nil }

func (x *JWTKeyEntry) GetStatus() Status { _ = "STUB: not implemented"; return *new(Status) }

func (x *JWTKeyEntry) GetAuthorityId() string { _ = "STUB: not implemented"; return "" }

type WITKeyEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which WIT Key slot this entry occupied.
	SlotId string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// When the key was issued (unix epoch in seconds)
	IssuedAt int64 `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// When the key expires unix epoch in seconds)
	NotAfter int64 `protobuf:"varint,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// WIT key id (i.e. "kid" claim)
	Kid string `protobuf:"bytes,4,opt,name=kid,proto3" json:"kid,omitempty"`
	// PKIX encoded public key
	PublicKey []byte `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The entry status
	Status Status `protobuf:"varint,6,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	// The WIT key ID
	AuthorityId   string `protobuf:"bytes,7,opt,name=authority_id,json=authorityId,proto3" json:"authority_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WITKeyEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *WITKeyEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*WITKeyEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WITKeyEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WITKeyEntry.ProtoReflect.Descriptor instead.
func (*WITKeyEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WITKeyEntry) GetSlotId() string { _ = "STUB: not implemented"; return "" }

func (x *WITKeyEntry) GetIssuedAt() int64 { _ = "STUB: not implemented"; return 0 }

func (x *WITKeyEntry) GetNotAfter() int64 { _ = "STUB: not implemented"; return 0 }

func (x *WITKeyEntry) GetKid() string { _ = "STUB: not implemented"; return "" }

func (x *WITKeyEntry) GetPublicKey() []byte { _ = "STUB: not implemented"; return nil }

func (x *WITKeyEntry) GetStatus() Status { _ = "STUB: not implemented"; return *new(Status) }

func (x *WITKeyEntry) GetAuthorityId() string { _ = "STUB: not implemented"; return "" }

type Entries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X509CAs       []*X509CAEntry         `protobuf:"bytes,1,rep,name=x509CAs,proto3" json:"x509CAs,omitempty"`
	JwtKeys       []*JWTKeyEntry         `protobuf:"bytes,2,rep,name=jwtKeys,proto3" json:"jwtKeys,omitempty"`
	WitKeys       []*WITKeyEntry         `protobuf:"bytes,3,rep,name=witKeys,proto3" json:"witKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entries) Reset() { _ = "STUB: not implemented"; return }

func (x *Entries) String() string { _ = "STUB: not implemented"; return "" }

func (*Entries) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Entries) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Entries.ProtoReflect.Descriptor instead.
func (*Entries) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Entries) GetX509CAs() []*X509CAEntry { _ = "STUB: not implemented"; return nil }

func (x *Entries) GetJwtKeys() []*JWTKeyEntry { _ = "STUB: not implemented"; return nil }

func (x *Entries) GetWitKeys() []*WITKeyEntry { _ = "STUB: not implemented"; return nil }

var File_private_server_journal_journal_proto protoreflect.FileDescriptor

const file_private_server_journal_journal_proto_rawDesc = "" +
	"\n" +
	"$private/server/journal/journal.proto\"\xa1\x02\n" +
	"\vX509CAEntry\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt\x12 \n" +
	"\vcertificate\x18\x03 \x01(\fR\vcertificate\x12%\n" +
	"\x0eupstream_chain\x18\x04 \x03(\fR\rupstreamChain\x12\x1f\n" +
	"\x06status\x18\x05 \x01(\x0e2\a.StatusR\x06status\x12!\n" +
	"\fauthority_id\x18\x06 \x01(\tR\vauthorityId\x12\x1b\n" +
	"\tnot_after\x18\a \x01(\x03R\bnotAfter\x122\n" +
	"\x15upstream_authority_id\x18\b \x01(\tR\x13upstreamAuthorityId\"\xd5\x01\n" +
	"\vJWTKeyEntry\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt\x12\x1b\n" +
	"\tnot_after\x18\x03 \x01(\x03R\bnotAfter\x12\x10\n" +
	"\x03kid\x18\x04 \x01(\tR\x03kid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\x06status\x18\x06 \x01(\x0e2\a.StatusR\x06status\x12!\n" +
	"\fauthority_id\x18\a \x01(\tR\vauthorityId\"\xd5\x01\n" +
	"\vWITKeyEntry\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt\x12\x1b\n" +
	"\tnot_after\x18\x03 \x01(\x03R\bnotAfter\x12\x10\n" +
	"\x03kid\x18\x04 \x01(\tR\x03kid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\x06status\x18\x06 \x01(\x0e2\a.StatusR\x06status\x12!\n" +
	"\fauthority_id\x18\a \x01(\tR\vauthorityId\"\x81\x01\n" +
	"\aEntries\x12&\n" +
	"\ax509CAs\x18\x01 \x03(\v2\f.X509CAEntryR\ax509CAs\x12&\n" +
	"\ajwtKeys\x18\x02 \x03(\v2\f.JWTKeyEntryR\ajwtKeys\x12&\n" +
	"\awitKeys\x18\x03 \x03(\v2\f.WITKeyEntryR\awitKeys*8\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bPREPARED\x10\x02\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03\x12\a\n" +
	"\x03OLD\x10\x04B6Z4github.com/spiffe/spire/proto/private/server/journalb\x06proto3"

var (
	file_private_server_journal_journal_proto_rawDescOnce sync.Once
	file_private_server_journal_journal_proto_rawDescData []byte
)

func file_private_server_journal_journal_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_private_server_journal_journal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_private_server_journal_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_private_server_journal_journal_proto_goTypes = []any{
	(Status)(0),         // 0: Status
	(*X509CAEntry)(nil), // 1: X509CAEntry
	(*JWTKeyEntry)(nil), // 2: JWTKeyEntry
	(*WITKeyEntry)(nil), // 3: WITKeyEntry
	(*Entries)(nil),     // 4: Entries
}
var file_private_server_journal_journal_proto_depIdxs = []int32{
	0, // 0: X509CAEntry.status:type_name -> Status
	0, // 1: JWTKeyEntry.status:type_name -> Status
	0, // 2: WITKeyEntry.status:type_name -> Status
	1, // 3: Entries.x509CAs:type_name -> X509CAEntry
	2, // 4: Entries.jwtKeys:type_name -> JWTKeyEntry
	3, // 5: Entries.witKeys:type_name -> WITKeyEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init()                                           { file_private_server_journal_journal_proto_init() }
func file_private_server_journal_journal_proto_init() { _ = "STUB: not implemented"; return }
